openapi: 3.0.0
info:
  title: 'Laravel API'
  description: ''
  contact:
    name: 'Tuyen DN'
    url: ''
    email: ''
  version: v1
paths:
  /api/login:
    post:
      tags:
        - Login
      summary: 'Đăng nhập'
      operationId: e72a9ff4bacb2b244b7cf75848e6e333
      parameters:
        -
          $ref: '#/components/parameters/api_key'
        -
          $ref: '#/components/parameters/screen_id'
        -
          name: email
          in: query
          description: email
          schema:
            type: string
            example: ''
        -
          name: password
          in: query
          description: password
          schema:
            type: string
            example: ''
      responses:
        200:
          description: 'Thành công'
        401:
          description: Unauthorized
  /api/category:
    get:
      tags:
        - Category
      summary: 'Get thông tin category'
      operationId: 6f8ce85b32d29d1a802206cacd2915ab
      parameters:
        -
          $ref: '#/components/parameters/api_key'
        -
          $ref: '#/components/parameters/screen_id'
      responses:
        200:
          description: 'Thành công'
        401:
          description: Unauthorized
      security:
        -
          bearerAuth: []
  /api/category/create:
    post:
      tags:
        - Category
      summary: 'Lưu thông tin category'
      operationId: 42277a891a5d9d947b469bd6f3e0254c
      parameters:
        -
          $ref: '#/components/parameters/api_key'
        -
          $ref: '#/components/parameters/screen_id'
        -
          name: name
          in: query
          description: name
          schema:
            type: string
            example: ''
        -
          name: slug
          in: query
          description: slug
          schema:
            type: string
            example: ''
        -
          name: meta_description
          in: query
          description: meta_description
          schema:
            type: string
            example: ''
        -
          name: seo_title
          in: query
          description: seo_title
          schema:
            type: string
            example: ''
      responses:
        200:
          description: 'Thành công'
        401:
          description: Unauthorized
      security:
        -
          bearerAuth: []
  /api/category/update:
    post:
      tags:
        - Category
      summary: 'Update category'
      operationId: bddd6f6b0c398d385fc472c0bd5aa008
      parameters:
        -
          $ref: '#/components/parameters/api_key'
        -
          $ref: '#/components/parameters/screen_id'
        -
          name: id
          in: query
          description: id
          schema:
            type: string
            example: ''
        -
          name: name
          in: query
          description: name
          schema:
            type: string
            example: ''
        -
          name: slug
          in: query
          description: slug
          schema:
            type: string
            example: ''
        -
          name: meta_description
          in: query
          description: meta_description
          schema:
            type: string
            example: ''
        -
          name: seo_title
          in: query
          description: seo_title
          schema:
            type: string
            example: ''
      responses:
        200:
          description: 'Thành công'
          content:
            application/json:
              schema:
                properties:
                  errors:
                    type: array
                    items:
                      type: string
                  data:
                    properties:
                      key1:
                        type: string
                      key2:
                        type: integer
                    type: object
                type: object
      security:
        -
          bearerAuth: []
  /api/category/delete:
    post:
      tags:
        - Category
      summary: 'Delete thông tin category'
      operationId: 26b8a1f9c3a75ee228eecdd9a6ad727d
      parameters:
        -
          $ref: '#/components/parameters/api_key'
        -
          $ref: '#/components/parameters/screen_id'
        -
          name: id
          in: query
          description: id
          schema:
            type: string
            example: ''
      responses:
        200:
          description: 'Thành công'
        401:
          description: Unauthorized
      security:
        -
          bearerAuth: []
  /api/product:
    get:
      tags:
        - Product
      summary: 'Get thông tin product'
      operationId: a6115629295f5748353f7cbd0f801c5a
      parameters:
        -
          $ref: '#/components/parameters/api_key'
        -
          $ref: '#/components/parameters/screen_id'
      responses:
        200:
          description: 'Thành công'
        401:
          description: Unauthorized
      security:
        -
          bearerAuth: []
  /api/product/create:
    post:
      tags:
        - Product
      summary: 'Lưu thông tin product'
      operationId: 9c3ef740add78c4843545c325047cd1d
      parameters:
        -
          $ref: '#/components/parameters/api_key'
        -
          $ref: '#/components/parameters/screen_id'
        -
          name: category_id
          in: query
          description: category_id
          schema:
            type: string
            example: ''
        -
          name: name
          in: query
          description: name
          schema:
            type: string
            example: ''
        -
          name: description
          in: query
          description: description
          schema:
            type: string
            example: ''
        -
          name: price
          in: query
          description: price
          schema:
            type: string
            example: ''
        -
          name: total_sales
          in: query
          description: total_sales
          schema:
            type: string
            example: ''
        -
          name: rating
          in: query
          description: rating
          schema:
            type: string
            example: ''
        -
          name: image_url
          in: query
          description: image_url
          schema:
            type: string
            example: ''
        -
          name: brands
          in: query
          description: brands
          schema:
            type: string
            example: ''
        -
          name: seo_title
          in: query
          description: seo_title
          schema:
            type: string
            example: ''
        -
          name: seo_description
          in: query
          description: seo_description
          schema:
            type: string
            example: ''
        -
          name: seo_slug
          in: query
          description: seo_slug
          schema:
            type: string
            example: ''
      responses:
        200:
          description: 'Thành công'
        401:
          description: Unauthorized
      security:
        -
          bearerAuth: []
  /api/product/update:
    post:
      tags:
        - Product
      summary: 'Update product'
      operationId: 4fe0fb8744f51da34ebf659000e3beb9
      parameters:
        -
          $ref: '#/components/parameters/api_key'
        -
          $ref: '#/components/parameters/screen_id'
        -
          name: product_id
          in: query
          description: product_id
          schema:
            type: string
            example: ''
        -
          name: category_id
          in: query
          description: category_id
          schema:
            type: string
            example: ''
        -
          name: name
          in: query
          description: name
          schema:
            type: string
            example: ''
        -
          name: description
          in: query
          description: description
          schema:
            type: string
            example: ''
        -
          name: price
          in: query
          description: price
          schema:
            type: string
            example: ''
        -
          name: total_sales
          in: query
          description: total_sales
          schema:
            type: string
            example: ''
        -
          name: rating
          in: query
          description: rating
          schema:
            type: string
            example: ''
        -
          name: image_url
          in: query
          description: image_url
          schema:
            type: string
            example: ''
        -
          name: brands
          in: query
          description: brands
          schema:
            type: string
            example: ''
        -
          name: seo_title
          in: query
          description: seo_title
          schema:
            type: string
            example: ''
        -
          name: seo_description
          in: query
          description: seo_description
          schema:
            type: string
            example: ''
        -
          name: seo_slug
          in: query
          description: seo_slug
          schema:
            type: string
            example: ''
      responses:
        200:
          description: 'Thành công'
        401:
          description: Unauthorized
      security:
        -
          bearerAuth: []
  /api/product/delete:
    post:
      tags:
        - Product
      summary: 'Delete thông tin product'
      operationId: bffbc883865b2a377e93c3ac70edc262
      parameters:
        -
          $ref: '#/components/parameters/api_key'
        -
          $ref: '#/components/parameters/screen_id'
        -
          name: product_id
          in: query
          description: product_id
          schema:
            type: string
            example: ''
      responses:
        200:
          description: 'Thành công'
        401:
          description: Unauthorized
      security:
        -
          bearerAuth: []
components:
  responses:
    401:
      description: Unauthorized
  parameters:
    api_key:
      name: x-api-key
      in: header
      description: 'Key for client access API'
      required: true
      schema:
        type: string
        example: 4GdyrjbCaemU7J6AB7YMVGapkkg3Tk6+UI/fJ7NeFPc=
    screen_id:
      name: x-screen-id
      in: header
      description: 'Id of screen call API'
      schema:
        type: string
        example: Swagger
  examples:
    invalid_data:
      summary: 'Invalid data'
      value:
        code: 400
        messageNo: E001
        message: 項目が入力されていません
        invalidData:
          username:
            - E001
            - E002
    bad_request:
      summary: 'Bad request'
      value:
        code: 400
        messageNo: E400
        message: エラーが発生しました。もう一度お願いします。
    not_auth:
      summary: 'Not authentication'
      value:
        code: 401
        messageNo: E401
        message: ログインセッションの有効期限が切れています。もう一度ログインしてください。
    not_access:
      summary: 'Not access'
      value:
        code: 403
        messageNo: E403
        message: この機能にアクセスする権限がありません。
    not_acceptable:
      summary: 'Not Acceptable'
      value:
        code: 406
        messageNo: E406
        message: 項目が入力されていません
    exception:
      summary: Exception
      value:
        code: 500
        messageNo: E500
        message: エラーが発生しました。もう一度お願いします。
        dataErrors:
          instance: ErrorException
          line: 37
          file: LoginModel.php
          code: 0
          message: 'Undefined array key companycode'
  securitySchemes:
    bearerAuth:
      type: http
      name: bearerAuth
      in: header
      bearerFormat: JWT
      scheme: bearer
tags:
  -
    name: Login
    description: Login
  -
    name: Category
    description: Category
  -
    name: Product
    description: Product
security:
  security:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
